name: CI
on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*
jobs:
  build:
    name: Format and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.24
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: Check Go Format
        run: |
          gofmtFiles=$(gofmt -l .)
          if [ "${#gofmtFiles}" -ne "0" ]; then
            echo "gofmt failed"
            exit 1
          fi
      - name: Build
        run: ./scripts/build_arm64.sh
      - name: Upload binary
        if: startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/rpi-pwm-fancontrol
          asset_name: rpi-pwm-fancontrol
          tag: ${{ github.ref }}
          overwrite: true
          body: "arm64 build"
